version: '2'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    networks:
      - rede_jenkins
    ports:
      - 8000:8000
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    expose: 
      - 8000

  app:
    restart: always
    build: .
    networks:
      - rede_jenkins
    volumes: 
      - ./src:/src
      - ./pom.xml:/pom.xml
    expose:
      - "8080"
    command: mvn clean package spring-boot:run
networks:
  rede_jenkins:
    external: true